# Generated by Django 4.2.3 on 2023-08-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passport_photograph',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state_of_origin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_fee_paid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year_of_admission',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
